# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cacheboard Technology LLP
email: cacheboard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A mix of Traders and Technologists using Market Research to invest in stocks and derivatives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cacheboard.in" # the base hostname & protocol for your site
twitter_username: cacheboard
github_username:  cacheboard

# Build settings
markdown: kramdown
